In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
df = pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
grouped_data = df.groupby("Species")

In [4]:
summary_data = grouped_data.agg({'PetalWidthCm': ['mean', 'median', 'min', 'max', 'std'],
                                 'PetalLengthCm': ['mean', 'median', 'min', 'max', 'std'],
                                'SepalWidthCm' : ['mean', 'median', 'min', 'max', 'std'],
                                'SepalLengthCm': ['mean', 'median', 'min', 'max', 'std']})
summary_data

                PetalWidthCm                            PetalLengthCm         \
                        mean median  min  max       std          mean median
Species
Iris-setosa            0.244    0.2  0.1  0.6  0.107210         1.464   1.50
Iris-versicolor        1.326    1.3  1.0  1.8  0.197753         4.260   4.35
Iris-virginica         2.026    2.0  1.4  2.5  0.274650         5.552   5.55

                                    SepalWidthCm                             \
                 min  max       std         mean median  min  max       std
Species
Iris-setosa      1.0  1.9  0.173511        3.418    3.4  2.3  4.4  0.381024
Iris-versicolor  3.0  5.1  0.469911        2.770    2.8  2.0  3.4  0.313798
Iris-virginica   4.5  6.9  0.551895        2.974    3.0  2.2  3.8  0.322497

                SepalLengthCm
                         mean median  min  max       std
Species
Iris-setosa             5.006    5.0  4.3  5.8  0.352490
Iris-versicolor         5.936    5.9  4.9  7.0  0.516171
Iris-virginica          6.588    6.5  4.9  7.9  0.635880

Percentile:-

In [6]:
summary_data = grouped_data.agg({
    'PetalWidthCm': [
        ('25%', lambda x: x.quantile(0.25)),
        ('50%', lambda x: x.quantile(0.5)),
        ('75%', lambda x: x.quantile(0.75))
    ],
    'PetalLengthCm': [
        ('25%', lambda x: x.quantile(0.25)),
        ('50%', lambda x: x.quantile(0.5)),
        ('75%', lambda x: x.quantile(0.75))
    ],
    'SepalWidthCm': [
        ('25%', lambda x: x.quantile(0.25)),
        ('50%', lambda x: x.quantile(0.5)),
        ('75%', lambda x: x.quantile(0.75))
    ],'SepalLengthCm': [
        ('25%', lambda x: x.quantile(0.25)),
        ('50%', lambda x: x.quantile(0.5)),
        ('75%', lambda x: x.quantile(0.75))
    ]
})
summary_data

                PetalWidthCm           PetalLengthCm               \
                         25%  50%  75%           25%   50%    75%
Species
Iris-setosa              0.2  0.2  0.3           1.4  1.50  1.575
Iris-versicolor          1.2  1.3  1.5           4.0  4.35  4.600
Iris-virginica           1.8  2.0  2.3           5.1  5.55  5.875

                SepalWidthCm             SepalLengthCm
                         25%  50%    75%           25%  50%  75%
Species
Iris-setosa            3.125  3.4  3.675         4.800  5.0  5.2
Iris-versicolor        2.525  2.8  3.000         5.600  5.9  6.3
Iris-virginica         2.800  3.0  3.175         6.225  6.5  6.9